name: QA

on:
  push:
    branches:
      - '**'

jobs:
  check-code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Set up Python 3
        run: uv python install 3.12

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v4

      - name: Install dependencies
        run: rye sync

      - name: Install dependencies
        run: |
          rye install pre-commit --force
          rye install commitizen --force
          rye install docformatter --features tomli --force

      - name: Check commit message with Commitizen
        run: rye run cz check -m "${{ github.event.head_commit.message }}"

      - name: Run docformatter
        run: rye run docformatter --check --config ./pyproject.toml .

      - name: Run pre-commit checks
        run: rye run pre-commit run --all-files

      - name: After script
        run: echo "Pre-commit checks completed."
